#!/bin/bash

if [[ $INITIALIZE == yes ]]; then

  ## prepare data directory
  if [[ ! -d /var/lib/mysql/mysql ]]; then
    echo data directory does not exist... rebuilding...
    mysql_install_db > /dev/null 2>&1 || exit 127
    echo rebuilding finished
    echo creating user: datamaster
    service mysql start || exit 127
    mysql -u root -e "CREATE USER '$MYUSER'@'localhost' IDENTIFIED BY '$MYPASS';"
    mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '$MYUSER'@'localhost';"
  fi

  ## set httpd port

  echo "setting http port to $HTTPPORT ..."

  awk '/LISTEN/{print "Listen "'$HTTPPORT';next}
       /DEFAULTHOST/{print "<VirtualHost *:'$HTTPPORT'>";next}
       {print}' /root/tapache2.conf > /etc/apache2/apache2.conf

  service apache2 start
  service mysql restart
  echo $MYUSER password: $MYPASS

else
  echo skipping initialization
  echo the services are not running..
fi

echo sleep and listen...
while true; do echo zzzZZZzzzZZZzzz; sleep 1000; done
